### ISSUE TITLE
Login failed!

### ISSUE THREAD

**Issue by endriazizi** [noodlio/noodlio-pay-ionic-example#2]
Hello,
I got this error:

`services-auth.js:21 Login failed! Error: Projects created at console.firebase.google.com must use the new Firebase Authentication SDKs available from firebase.google.com/docs/auth/`

Could someone help me, please.

**Comment by archive-a1** [comment]
This is due to the new Firebase console. We are working on an update.

**Comment by archive-a1** [comment]
The starter has been updated to support Firebase V3. Please refer to the latest update to resolve your mentioned issue:
https://www.noodl.io/market/product/P201702052311456/ionic-shop-advanced-with-firebase-v3-advanced-ecommerce-template-with-stripe-payments-and-admin
