### ISSUE TITLE
Cannot read property 'extend'

### ISSUE THREAD

**Issue by carlosalvarez91** [noodlio/noodlio-pay-ionic-example#4]
Console says:
`angular-stripe-checkout.js:40Uncaught TypeError: Cannot read property 'extend' of undefined(…)(anonymous function) @ angular-stripe-checkout.js:40(anonymous function) @ angular-stripe-checkout.js:216
VM17358:1 Uncaught DOMException: Blocked a frame with origin "https://js.stripe.com" from accessing a cross-origin frame.(…)(anonymous function) @ VM17358:1`

I really don't know how to solve it, the problem becomes when I integrate the checkout example in my app.

**Comment by noodlio** [comment]
White-listing the origin should fix the issue: http://legacy.docs.ionic.io/v1.0/docs/cordova-whitelist
